name: Weather Bot Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *' # Runs daily at 9:00 AM UTC

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        
      - name: Install NPM Dependencies
        run: npm install

      - name: Run Weather Bot
        run: node index.js
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          WEATHER_SECRET: ${{ secrets.WEATHER_SECRET }}
          PORT: ${{ secrets.PORT }}
          LAT: ${{ secrets.LAT }}
          LON: ${{ secrets.LON }}
