name: Weather Bot Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: '0 9 * * *' # Runs daily at 9:00 AM UTC

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v3

            - name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '16'

            - name: Install dependencies
                run: npm install

            - name: Run Weather Bot
                run: node Bot/index.js
